import { StyleSheet } from 'react-native';
import { PharmacyColors, CommonStyles } from '../constants/Colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: PharmacyColors.background },
  header: { paddingTop: 20, paddingBottom: 24, paddingHorizontal: 20, borderBottomLeftRadius: 20, borderBottomRightRadius: 20 },
  headerContent: { flexDirection: 'row', alignItems: 'center' },
  backButton: { marginRight: 16 },
  headerTitle: { fontSize: 24, fontWeight: 'bold', color: PharmacyColors.white },
  content: { flex: 1, paddingTop: 20 },
  section: { backgroundColor: PharmacyColors.white, marginHorizontal: 20, marginBottom: 20, borderRadius: 16, padding: 16, ...CommonStyles.shadow },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: PharmacyColors.textPrimary, marginBottom: 16 },
  addressCard: { backgroundColor: PharmacyColors.lightGray, borderRadius: 12, padding: 16, marginBottom: 12 },
  addressHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  labelContainer: { flexDirection: 'row', alignItems: 'center' },
  addressLabel: { fontSize: 16, fontWeight: '600', color: PharmacyColors.textPrimary, marginLeft: 8 },
  addressText: { fontSize: 14, color: PharmacyColors.textSecondary, marginBottom: 12 },
  defaultBadge: { backgroundColor: PharmacyColors.success + '20', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  defaultText: { fontSize: 12, color: PharmacyColors.success, fontWeight: '600' },
  addressActions: { flexDirection: 'row', justifyContent: 'flex-end' },
  actionButton: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, backgroundColor: PharmacyColors.accent + '20', marginLeft: 8 },
  actionButtonText: { fontSize: 14, color: PharmacyColors.accent, fontWeight: '600' },
  deleteButton: { backgroundColor: PharmacyColors.error + '20' },
  deleteButtonText: { color: PharmacyColors.error },
  addButton: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', padding: 16, borderWidth: 2, borderColor: PharmacyColors.accent + '40', borderStyle: 'dashed', borderRadius: 12 },
  addButtonText: { fontSize: 16, color: PharmacyColors.accent, fontWeight: '600', marginLeft: 8 },
  formContainer: { padding: 16 },
  formTitle: { fontSize: 18, fontWeight: 'bold', color: PharmacyColors.textPrimary, marginBottom: 20 },
  inputGroup: { marginBottom: 16 },
  label: { fontSize: 14, color: PharmacyColors.textSecondary, marginBottom: 8 },
  input: { backgroundColor: PharmacyColors.lightGray, borderRadius: 12, padding: 12, fontSize: 16, color: PharmacyColors.textPrimary },
  addressInput: { height: 100, textAlignVertical: 'top' },
  formActions: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 20 },
  formButton: { paddingHorizontal: 24, paddingVertical: 12, borderRadius: 25, marginLeft: 12 },
  cancelButton: { backgroundColor: PharmacyColors.gray + '20' },
  cancelButtonText: { fontSize: 16, color: PharmacyColors.gray, fontWeight: '600' },
  saveButton: { backgroundColor: PharmacyColors.accent },
  saveButtonText: { fontSize: 16, color: PharmacyColors.white, fontWeight: '600' },
});
