import { StyleSheet } from 'react-native';
import { PharmacyColors, CommonStyles } from '../constants/Colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: PharmacyColors.background,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  header: {
    paddingTop: 50,
    paddingBottom: 40,
    paddingHorizontal: 30,
  },
  headerContent: {
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: 'bold',
    color: PharmacyColors.white,
    marginBottom: 8,
  },
  headerSubtitle: {
    fontSize: 16,
    color: PharmacyColors.white,
    opacity: 0.95,
    textAlign: 'center',
  },
  formContainer: {
    flex: 1,
    marginTop: -20,
    paddingHorizontal: 20,
  },
  formCard: {
    backgroundColor: PharmacyColors.white,
    borderRadius: 20,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  input: {
    marginBottom: 8,
    backgroundColor: PharmacyColors.white,
  },
  errorText: {
    color: PharmacyColors.error,
    fontSize: 12,
    marginBottom: 12,
    marginLeft: 4,
  },
  forgotPassword: {
    alignSelf: 'flex-end',
    marginBottom: 20,
  },
  forgotPasswordText: {
    color: PharmacyColors.accent,
    fontSize: 14,
    fontWeight: '600',
  },
  loginButton: {
    paddingVertical: 16,
    borderRadius: 30,
    alignItems: 'center',
    shadowColor: PharmacyColors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  registerButton: {
    paddingVertical: 16,
    borderRadius: 30,
    alignItems: 'center',
    shadowColor: PharmacyColors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  buttonDisabled: { opacity: 0.6 },
  loginButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: PharmacyColors.white,
  },
  registerButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: PharmacyColors.white,
  },
  divider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 24,
  },
  dividerLine: { flex: 1, height: 1, backgroundColor: PharmacyColors.borderGray },
  dividerText: { marginHorizontal: 16, color: PharmacyColors.gray, fontSize: 14 },
  registerContainer: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  registerText: { color: PharmacyColors.textSecondary, fontSize: 15 },
  registerLink: { color: PharmacyColors.accent, fontSize: 15, fontWeight: 'bold' },

  // Forgot password specific
  successHeader: { paddingTop: 50, paddingBottom: 20, paddingHorizontal: 20 },
  successContainer: { flex: 1, alignItems: 'center', paddingHorizontal: 30, paddingTop: 40 },
  successIconGradient: {
    width: 120,
    height: 120,
    borderRadius: 60,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: PharmacyColors.success,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  successTitle: { fontSize: 28, fontWeight: 'bold', color: PharmacyColors.textPrimary, marginBottom: 16, textAlign: 'center' },
  successMessage: { fontSize: 15, color: PharmacyColors.textSecondary, textAlign: 'center', lineHeight: 22, marginBottom: 40 },
  emailText: { fontWeight: 'bold', color: PharmacyColors.accent },
  infoBox: { flexDirection: 'row', alignItems: 'center', backgroundColor: PharmacyColors.info + '10', padding: 12, borderRadius: 12, marginBottom: 24 },
  infoText: { flex: 1, fontSize: 13, color: PharmacyColors.textSecondary, marginLeft: 10, lineHeight: 18 },
  submitButton: { flexDirection: 'row', paddingVertical: 16, borderRadius: 30, alignItems: 'center', justifyContent: 'center', shadowColor: PharmacyColors.accent, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.3, shadowRadius: 6, elevation: 5 },
  submitButtonText: { fontSize: 16, fontWeight: 'bold', color: PharmacyColors.white, marginRight: 8 },
  backToLoginOutline: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 14, borderRadius: 30, borderWidth: 2, borderColor: PharmacyColors.accent },
  backToLoginOutlineText: { fontSize: 16, fontWeight: '600', color: PharmacyColors.accent, marginLeft: 8 },
  resendContainer: { flexDirection: 'row', alignItems: 'center' },
  resendText: { fontSize: 14, color: PharmacyColors.textSecondary },
  resendLink: { fontSize: 14, fontWeight: 'bold', color: PharmacyColors.accent },
});
