import { StyleSheet } from 'react-native';
import { PharmacyColors, CommonStyles } from '../constants/Colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: PharmacyColors.background },
  content: { flex: 1 },
  header: { paddingTop: 20, paddingBottom: 24, paddingHorizontal: 20, borderBottomLeftRadius: 20, borderBottomRightRadius: 20 },
  searchContainer: { marginTop: 16, marginBottom: 8 },
  searchInputContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: PharmacyColors.white, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 8, ...CommonStyles.shadow },
  searchIcon: { marginRight: 8 },
  searchInput: { flex: 1, fontSize: 16, color: PharmacyColors.textPrimary, paddingVertical: 4 },
  clearButton: { padding: 4 },
  headerTitle: { fontSize: 28, fontWeight: 'bold', color: PharmacyColors.white, marginBottom: 6 },
  headerSubtitle: { fontSize: 15, color: PharmacyColors.white, opacity: 0.9, marginBottom: 16 },
  uploadSection: { paddingHorizontal: 20, marginTop: 24, marginBottom: 24 },
  sectionTitle: { fontSize: 20, fontWeight: 'bold', color: PharmacyColors.textPrimary, marginBottom: 16 },
  uploadCard: { borderRadius: 20, overflow: 'hidden', marginBottom: 24, ...CommonStyles.shadowMedium },
  uploadCardGradient: { padding: 24, alignItems: 'center' },
  uploadIconContainer: { marginBottom: 20 },
  uploadIcon: { width: 80, height: 80, borderRadius: 40, justifyContent: 'center', alignItems: 'center' },
  uploadTitle: { fontSize: 20, fontWeight: 'bold', color: PharmacyColors.textPrimary, marginBottom: 8, textAlign: 'center' },
  uploadDescription: { fontSize: 14, color: PharmacyColors.textSecondary, textAlign: 'center', lineHeight: 20, marginBottom: 20 },
  uploadButton: { flexDirection: 'row', alignItems: 'center', backgroundColor: PharmacyColors.white, paddingVertical: 12, paddingHorizontal: 24, borderRadius: 25, ...CommonStyles.shadow },
  uploadButtonText: { fontSize: 16, fontWeight: 'bold', color: PharmacyColors.accent, marginRight: 8 },
  benefitsContainer: { backgroundColor: PharmacyColors.white, borderRadius: 16, padding: 20, ...CommonStyles.shadow },
  benefitsTitle: { fontSize: 16, fontWeight: 'bold', color: PharmacyColors.textPrimary, marginBottom: 16 },
  benefitItem: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  benefitIconContainer: { marginRight: 12 },
  benefitText: { flex: 1, fontSize: 14, color: PharmacyColors.textSecondary, lineHeight: 20 },
  howItWorksSection: { paddingHorizontal: 20, marginBottom: 24 },
  stepContainer: { flexDirection: 'row', marginBottom: 20 },
  stepNumber: { width: 36, height: 36, borderRadius: 18, backgroundColor: PharmacyColors.accent, justifyContent: 'center', alignItems: 'center', marginRight: 16 },
  stepNumberText: { fontSize: 16, fontWeight: 'bold', color: PharmacyColors.white },
  stepContent: { flex: 1 },
  stepTitle: { fontSize: 16, fontWeight: '600', color: PharmacyColors.textPrimary, marginBottom: 4 },
  stepDescription: { fontSize: 14, color: PharmacyColors.textSecondary, lineHeight: 20 },
  bottomSpacing: { height: 30 },
});
