import { StyleSheet } from 'react-native';
import { PharmacyColors, CommonStyles } from '../constants/Colors';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: PharmacyColors.background },
  customHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: 50, paddingBottom: 16, paddingHorizontal: 20 },
  backButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255, 255, 255, 0.2)', justifyContent: 'center', alignItems: 'center' },
  favoriteButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: 'rgba(255, 255, 255, 0.2)', justifyContent: 'center', alignItems: 'center' },
  content: { flex: 1 },
  imageContainer: { backgroundColor: PharmacyColors.white, paddingVertical: 40, alignItems: 'center', position: 'relative', marginBottom: 20 },
  productEmoji: { fontSize: 120 },
  discountBadge: { position: 'absolute', top: 20, right: 20, backgroundColor: PharmacyColors.success, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  discountText: { fontSize: 12, fontWeight: 'bold', color: PharmacyColors.white },
  prescriptionBadge: { position: 'absolute', bottom: 20, flexDirection: 'row', alignItems: 'center', backgroundColor: PharmacyColors.error, paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20 },
  prescriptionText: { fontSize: 12, fontWeight: '600', color: PharmacyColors.white, marginLeft: 6 },
  infoContainer: { paddingHorizontal: 20 },
  categoryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  category: { fontSize: 14, color: PharmacyColors.accent, fontWeight: '600' },
  ratingContainer: { flexDirection: 'row', alignItems: 'center' },
  ratingText: { fontSize: 14, fontWeight: '600', color: PharmacyColors.textPrimary, marginLeft: 4 },
  reviewsText: { fontSize: 13, color: PharmacyColors.textSecondary, marginLeft: 4 },
  productName: { fontSize: 26, fontWeight: 'bold', color: PharmacyColors.textPrimary, marginBottom: 16, lineHeight: 32 },
  priceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 },
  priceContainer: { flexDirection: 'row', alignItems: 'center' },
  price: { fontSize: 32, fontWeight: 'bold', color: PharmacyColors.accent },
  originalPrice: { fontSize: 18, color: PharmacyColors.gray, textDecorationLine: 'line-through', marginLeft: 12 },
  stockContainer: { flexDirection: 'row', alignItems: 'center', backgroundColor: PharmacyColors.success + '20', paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  stockText: { fontSize: 13, fontWeight: '600', color: PharmacyColors.success, marginLeft: 4 },
  lowStockText: { color: PharmacyColors.warning },
  section: { marginBottom: 24 },
  sectionTitle: { fontSize: 18, fontWeight: 'bold', color: PharmacyColors.textPrimary, marginBottom: 12 },
  sectionText: { fontSize: 15, color: PharmacyColors.textSecondary, lineHeight: 22 },
  warningItem: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8 },
  warningText: { flex: 1, fontSize: 14, color: PharmacyColors.textSecondary, marginLeft: 8, lineHeight: 20 },
  additionalInfo: { backgroundColor: PharmacyColors.white, borderRadius: 16, padding: 16, marginBottom: 24, ...CommonStyles.shadow },
  infoRow: { marginBottom: 12 },
  infoLabel: { fontSize: 13, color: PharmacyColors.textSecondary, marginBottom: 4 },
  infoValue: { fontSize: 15, color: PharmacyColors.textPrimary, fontWeight: '600' },
  footer: { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: PharmacyColors.white, paddingHorizontal: 20, paddingTop: 16, paddingBottom: 20, borderTopWidth: 1, borderTopColor: PharmacyColors.borderGray, ...CommonStyles.shadowLarge },
  quantitySection: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  quantityLabel: { fontSize: 16, fontWeight: '600', color: PharmacyColors.textPrimary },
  quantityControls: { flexDirection: 'row', alignItems: 'center' },
  quantityButton: { width: 36, height: 36, borderRadius: 18, backgroundColor: PharmacyColors.accent + '20', justifyContent: 'center', alignItems: 'center' },
  quantityValue: { fontSize: 18, fontWeight: 'bold', color: PharmacyColors.textPrimary, marginHorizontal: 20, minWidth: 30, textAlign: 'center' },
  addToCartContainer: { width: '100%' },
  addToCartButton: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', paddingVertical: 16, borderRadius: 30 },
  addToCartText: { fontSize: 16, fontWeight: 'bold', color: PharmacyColors.white, marginLeft: 8, marginRight: 12 },
  addToCartPrice: { fontSize: 18, fontWeight: 'bold', color: PharmacyColors.white },
});
